font_size 10.0
window_padding_width 8
font_family      JetBrainsMono Nerd Font
italic_font      auto
bold_italic_font auto
include theme.conf
background_opacity 0.90
cursor_shape block
shell_integration no-cursor
cursor_trail 1
tab_bar_edge top
confirm_os_window_close 0

enabled_layouts splits

map ctrl+shift+enter launch --cwd=current --location=vsplit
map ctrl+alt+enter launch --cwd=current --location=hsplit
map ctrl+shift+left neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up neighboring_window up
map ctrl+shift+down neighboring_window down

map ctrl+alt+shift+left move_window left
map ctrl+alt+shift+right move_window right
map ctrl+alt+shift+up move_window up
map ctrl+alt+shift+down move_window down

map alt+f1 resize_window narrower
map alt+f2 resize_window wider
map alt+f3 resize_window taller
map alt+f4 resize_window shorter

map ctrl+alt+right next_tab
map ctrl+alt+left previous_tab
map ctrl+shift+d close_tab

map ctrl+f1 goto_session 
map ctrl+f2 goto_session empty_session.kitty-session
map ctrl+f3 goto_session my_session.kitty-session

#ligeratures are when == goes together
disable_ligatures never
map alt+l disable_ligatures_in all never
map alt+shift+l disable_ligatures_in all always

map alt+z change_font_size all +1
map alt+shift+z change_font_size all -1

map ctrl+tab next_window
