# https://wiki.hypr.land/Configuring/Variables/#animations
animations {
	enabled = yes

	animation = global, 1, 5, default
	animation = windows, 0
	animation = specialWorkspace, 1, 5, default, fade
}
