# exec-once = ~/.config/waybar/reload_waybar.sh
exec-once = ~/.config/quickshell/reload_qs.sh
exec-once = awww-daemon
exec-once = awww img -t none /home/martino/Pictures/Wallpapers/wallpaper06.png
exec-once = bluetoothctl power off
exec-once = systemctl --user start hyprpolkitagent
exec-once = xhost +si:localuser:root
exec-once = mako
