hl.on("hyprland.start", function () 
	-- hl.exec_cmd("~/.config/waybar/reload_waybar.sh")
	hl.exec_cmd("~/.config/quickshell/reload_qs.sh")
	hl.exec_cmd("awww-daemon --no-cache")
	hl.exec_cmd("awww img -t none /home/martino/Pictures/Wallpapers/lake_in_arch_logo.png")
	hl.exec_cmd("bluetoothctl power off")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("xhost +si:localuser:root")
	hl.exec_cmd("mako")
end)
