hl.on("hyprland.start", function () 
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd("~/.config/quickshell/reload_qs.sh")
	-- hl.exec_cmd("bluetoothctl power off")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("xhost +si:localuser:root")
	hl.exec_cmd("mako")
	hl.exec_cmd("change_wallpaper -ri")
	-- hl.exec_cmd("awww img -t none /home/martino/Pictures/Wallpapers/rapperswil_midnight_blue_distant.png")
end)
