exec-once = ~/.config/waybar/reload_waybar.sh
# exec-once = hyprpaper
exec-once = mpvpaper all -o "--loop no-audio --video-zoom=0.16" /home/martino/Pictures/Wallpapers/big_city.mp4
exec-once = bluetoothctl power off
exec-once = systemctl --user start hyprpolkitagent
exec-once = xhost +si:localuser:root
exec-once = mako
