# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
# "$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[mgr]
ratio          = [ 0, 2, 1 ]
sort_by        = "natural"
sort_sensitive = true
sort_reverse   = false
sort_dir_first = true
linemode       = "size_and_mtime"

[opener]
edit = [
	{ run = "vim %s", desc = "vim", block = true },
]
video = [
	{ run = "mpv %s", desc = "mpv", orphan = true },
]
open = [
	{ run = "xdg-open %s", desc = "xdg-open"},
]
pdf = [
	{ run = "zathura %s", orphan = true},
]
zen = [
	{ run = "zen-browser %s", orphan = true},
]
image = [
	{ run = "feh %s", desc = "Reveal", orphan = true },
]
extract = [
	{ run = "ya pub extract --list %s", desc = "Extract here" },
]
download = [
	{ run = "ya emit download --open %S", desc = "Download and open" },
]

[open]
rules = [
	# Folder
	{ url = "/*", use = [ ] },
	# Text
	{ mime = "text/*", use = [ "edit", "zen", "open" ] },
	# Image
	{ mime = "image/*", use = [ "image", "zen", "open"] },
	# Media
	{ mime = "{audio,video}/*", use = [ "video", "zen", "open" ] },
	# Pdf
	{ mime = "*/pdf", use = [ "pdf", "zen", "open" ] },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract" ] },
	# JSON
	{ mime = "application/{json,ndjson}", use = [ "edit", "zen", "open" ] },
	{ mime = "*/javascript", use = [ "edit", "zen", "open" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "open", "edit", "zen" ] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = ["download", "zen", "open"] },
	# Fallback 
	{ url = "*", use = [ "open", "edit", "zen" ] },
]
