source ~/vim/settings.vim
source ~/vim/remapping.vim
source ~/vim/plugs.vim
source ~/vim/colorizer.vim
source ~/vim/fzf.vim 
source ~/vim/indentline.vim 
source ~/vim/nerdtree.vim 
source ~/vim/vim-airline.vim
source ~/vim/vim-commentary.vim
source ~/vim/vimtex.vim
source ~/vim/ycm.vim

